services:
  universe_a:
    build:
      context: ./universeA
    volumes:
      - ./universeA:/app
      - /app/node_modules
    command:
      - npm
      - run
      - dev
    ports:
      - "3000:3000"
  universe_b:
    build:
      context: ./universeB
    volumes:
      - ./universeB:/app
      - /app/node_modules
    command:
      - npm
      - run
      - dev
    ports:
      - "3001:3001"
  translator:
    build:
      context: ./translator
    volumes:
      - ./translator:/app
    command:
      - npm
      - run
      - dev
    ports:
      - "3002:3002"
